# Generated by Django 3.2.6 on 2021-08-19 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_auto_20210816_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='section',
            field=models.CharField(choices=[('PM', 'POEM'), ('AT', 'ARTICLE'), ('YN', 'YARN')], max_length=100),
        ),
    ]
