# Generated by Django 3.2.6 on 2021-08-19 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_alter_post_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='section',
            field=models.CharField(choices=[('PM', 'POEM'), ('AT', 'ARTICLE'), ('YN', 'YARN'), ('TT', 'TEST')], max_length=100),
        ),
    ]
