# Generated by Django 3.2.6 on 2021-08-20 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0006_alter_post_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='section',
            field=models.CharField(choices=[('poem', 'POEM'), ('article', 'ARTICLE'), ('yarn', 'YARN')], max_length=100),
        ),
    ]
